//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_abutton_H
#define METASPRITE_abutton_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define abutton_TILE_ORIGIN 186
#define abutton_TILE_W 8
#define abutton_TILE_H 8
#define abutton_WIDTH 16
#define abutton_HEIGHT 16
#define abutton_TILE_COUNT 4
#define abutton_PALETTE_COUNT 1
#define abutton_COLORS_PER_PALETTE 4
#define abutton_TOTAL_COLORS 4
#define abutton_MAP_ATTRIBUTES 0
extern const unsigned char abutton_map[4];
#define abutton_map_attributes abutton_map

BANKREF_EXTERN(abutton)

extern const palette_color_t abutton_palettes[4];
extern const uint8_t abutton_tiles[64];

#endif
