//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#pragma bank 9

BANKREF(arrow)

const palette_color_t arrow_palettes[4] = {
	RGB8(  0,  0,  0), RGB8( 34, 32, 52), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	
};

const uint8_t arrow_tiles[16] = {
	0x00,0x00,0x08,0x00,
	0x0c,0x00,0x7e,0x00,
	0x7e,0x00,0x0c,0x00,
	0x08,0x00,0x00,0x00
	
};

const metasprite_t arrow_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const arrow_metasprites[1] = {
	arrow_metasprite0
};
