//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bbutton_H
#define METASPRITE_bbutton_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bbutton_TILE_ORIGIN 190
#define bbutton_TILE_W 8
#define bbutton_TILE_H 8
#define bbutton_WIDTH 16
#define bbutton_HEIGHT 16
#define bbutton_TILE_COUNT 4
#define bbutton_PALETTE_COUNT 1
#define bbutton_COLORS_PER_PALETTE 4
#define bbutton_TOTAL_COLORS 4
#define bbutton_MAP_ATTRIBUTES 0
extern const unsigned char bbutton_map[4];
#define bbutton_map_attributes bbutton_map

BANKREF_EXTERN(bbutton)

extern const palette_color_t bbutton_palettes[4];
extern const uint8_t bbutton_tiles[64];

#endif
