//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bellslogo_H
#define METASPRITE_bellslogo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bellslogo_TILE_ORIGIN 0
#define bellslogo_TILE_W 8
#define bellslogo_TILE_H 8
#define bellslogo_WIDTH 160
#define bellslogo_HEIGHT 144
#define bellslogo_TILE_COUNT 5
#define bellslogo_PALETTE_COUNT 1
#define bellslogo_COLORS_PER_PALETTE 4
#define bellslogo_TOTAL_COLORS 4
#define bellslogo_MAP_ATTRIBUTES bellslogo_map_attributes
#define bellslogo_MAP_ATTRIBUTES_WIDTH 20
#define bellslogo_MAP_ATTRIBUTES_HEIGHT 18
#define bellslogo_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define bellslogo_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char bellslogo_map[360];
extern const unsigned char bellslogo_map_attributes[360];

BANKREF_EXTERN(bellslogo)

extern const palette_color_t bellslogo_palettes[4];
extern const uint8_t bellslogo_tiles[80];

#endif
