//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bellscoin_H
#define METASPRITE_bellscoin_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bellscoin_TILE_ORIGIN 202
#define bellscoin_TILE_W 8
#define bellscoin_TILE_H 16
#define bellscoin_WIDTH 8
#define bellscoin_HEIGHT 32
#define bellscoin_TILE_COUNT 4
#define bellscoin_PALETTE_COUNT 1
#define bellscoin_COLORS_PER_PALETTE 4
#define bellscoin_TOTAL_COLORS 4
#define bellscoin_PIVOT_X 4
#define bellscoin_PIVOT_Y 16
#define bellscoin_PIVOT_W 8
#define bellscoin_PIVOT_H 32
extern const metasprite_t* const bellscoin_metasprites[1];

BANKREF_EXTERN(bellscoin)

extern const palette_color_t bellscoin_palettes[4];
extern const uint8_t bellscoin_tiles[64];

#endif
