//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bells_idle_H
#define METASPRITE_bells_idle_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bells_idle_TILE_ORIGIN 243
#define bells_idle_TILE_W 8
#define bells_idle_TILE_H 8
#define bells_idle_WIDTH 64
#define bells_idle_HEIGHT 56
#define bells_idle_TILE_COUNT 22
#define bells_idle_PALETTE_COUNT 1
#define bells_idle_COLORS_PER_PALETTE 4
#define bells_idle_TOTAL_COLORS 4
#define bells_idle_MAP_ATTRIBUTES 0
extern const unsigned char bells_idle_map[56];
#define bells_idle_map_attributes bells_idle_map

BANKREF_EXTERN(bells_idle)

extern const palette_color_t bells_idle_palettes[4];
extern const uint8_t bells_idle_tiles[352];

#endif
