//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bells_selfbonk_H
#define METASPRITE_bells_selfbonk_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bells_selfbonk_TILE_ORIGIN 202
#define bells_selfbonk_TILE_W 8
#define bells_selfbonk_TILE_H 8
#define bells_selfbonk_WIDTH 72
#define bells_selfbonk_HEIGHT 56
#define bells_selfbonk_TILE_COUNT 31
#define bells_selfbonk_PALETTE_COUNT 1
#define bells_selfbonk_COLORS_PER_PALETTE 4
#define bells_selfbonk_TOTAL_COLORS 4
#define bells_selfbonk_MAP_ATTRIBUTES 0
extern const unsigned char bells_selfbonk_map[63];
#define bells_selfbonk_map_attributes bells_selfbonk_map

BANKREF_EXTERN(bells_selfbonk)

extern const palette_color_t bells_selfbonk_palettes[4];
extern const uint8_t bells_selfbonk_tiles[496];

#endif
