//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bells_bonk_H
#define METASPRITE_bells_bonk_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bells_bonk_TILE_ORIGIN 137
#define bells_bonk_TILE_W 8
#define bells_bonk_TILE_H 8
#define bells_bonk_WIDTH 72
#define bells_bonk_HEIGHT 56
#define bells_bonk_TILE_COUNT 37
#define bells_bonk_PALETTE_COUNT 1
#define bells_bonk_COLORS_PER_PALETTE 4
#define bells_bonk_TOTAL_COLORS 4
#define bells_bonk_MAP_ATTRIBUTES 0
extern const unsigned char bells_bonk_map[63];
#define bells_bonk_map_attributes bells_bonk_map

BANKREF_EXTERN(bells_bonk)

extern const palette_color_t bells_bonk_palettes[4];
extern const uint8_t bells_bonk_tiles[592];

#endif
