//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bork_H
#define METASPRITE_bork_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bork_TILE_ORIGIN 0
#define bork_TILE_W 8
#define bork_TILE_H 8
#define bork_WIDTH 160
#define bork_HEIGHT 144
#define bork_TILE_COUNT 255
#define bork_PALETTE_COUNT 1
#define bork_COLORS_PER_PALETTE 4
#define bork_TOTAL_COLORS 4
#define bork_MAP_ATTRIBUTES bork_map_attributes
#define bork_MAP_ATTRIBUTES_WIDTH 20
#define bork_MAP_ATTRIBUTES_HEIGHT 18
#define bork_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define bork_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char bork_map[360];
extern const unsigned char bork_map_attributes[360];

BANKREF_EXTERN(bork)

extern const palette_color_t bork_palettes[4];
extern const uint8_t bork_tiles[4080];

#endif
