//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cheems_idle_H
#define METASPRITE_cheems_idle_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cheems_idle_TILE_ORIGIN 243
#define cheems_idle_TILE_W 8
#define cheems_idle_TILE_H 8
#define cheems_idle_WIDTH 64
#define cheems_idle_HEIGHT 56
#define cheems_idle_TILE_COUNT 37
#define cheems_idle_PALETTE_COUNT 1
#define cheems_idle_COLORS_PER_PALETTE 4
#define cheems_idle_TOTAL_COLORS 4
#define cheems_idle_MAP_ATTRIBUTES 0
extern const unsigned char cheems_idle_map[56];
#define cheems_idle_map_attributes cheems_idle_map

BANKREF_EXTERN(cheems_idle)

extern const palette_color_t cheems_idle_palettes[4];
extern const uint8_t cheems_idle_tiles[592];

#endif
