//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cheems_selfbonk_H
#define METASPRITE_cheems_selfbonk_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cheems_selfbonk_TILE_ORIGIN 202
#define cheems_selfbonk_TILE_W 8
#define cheems_selfbonk_TILE_H 8
#define cheems_selfbonk_WIDTH 72
#define cheems_selfbonk_HEIGHT 56
#define cheems_selfbonk_TILE_COUNT 40
#define cheems_selfbonk_PALETTE_COUNT 1
#define cheems_selfbonk_COLORS_PER_PALETTE 4
#define cheems_selfbonk_TOTAL_COLORS 4
#define cheems_selfbonk_MAP_ATTRIBUTES 0
extern const unsigned char cheems_selfbonk_map[63];
#define cheems_selfbonk_map_attributes cheems_selfbonk_map

BANKREF_EXTERN(cheems_selfbonk)

extern const palette_color_t cheems_selfbonk_palettes[4];
extern const uint8_t cheems_selfbonk_tiles[640];

#endif
