//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cheems_bonk_H
#define METASPRITE_cheems_bonk_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cheems_bonk_TILE_ORIGIN 137
#define cheems_bonk_TILE_W 8
#define cheems_bonk_TILE_H 8
#define cheems_bonk_WIDTH 72
#define cheems_bonk_HEIGHT 56
#define cheems_bonk_TILE_COUNT 46
#define cheems_bonk_PALETTE_COUNT 1
#define cheems_bonk_COLORS_PER_PALETTE 4
#define cheems_bonk_TOTAL_COLORS 4
#define cheems_bonk_MAP_ATTRIBUTES 0
extern const unsigned char cheems_bonk_map[63];
#define cheems_bonk_map_attributes cheems_bonk_map

BANKREF_EXTERN(cheems_bonk)

extern const palette_color_t cheems_bonk_palettes[4];
extern const uint8_t cheems_bonk_tiles[736];

#endif
