//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_chksum_H
#define METASPRITE_chksum_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define chksum_TILE_ORIGIN 150
#define chksum_TILE_W 8
#define chksum_TILE_H 8
#define chksum_WIDTH 24
#define chksum_HEIGHT 24
#define chksum_TILE_COUNT 9
#define chksum_PALETTE_COUNT 1
#define chksum_COLORS_PER_PALETTE 4
#define chksum_TOTAL_COLORS 4
#define chksum_MAP_ATTRIBUTES 0
extern const unsigned char chksum_map[9];
#define chksum_map_attributes chksum_map

BANKREF_EXTERN(chksum)

extern const palette_color_t chksum_palettes[4];
extern const uint8_t chksum_tiles[144];

#endif
