//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dogecoin_H
#define METASPRITE_dogecoin_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dogecoin_TILE_ORIGIN 202
#define dogecoin_TILE_W 8
#define dogecoin_TILE_H 16
#define dogecoin_WIDTH 8
#define dogecoin_HEIGHT 32
#define dogecoin_TILE_COUNT 4
#define dogecoin_PALETTE_COUNT 1
#define dogecoin_COLORS_PER_PALETTE 4
#define dogecoin_TOTAL_COLORS 4
#define dogecoin_PIVOT_X 4
#define dogecoin_PIVOT_Y 16
#define dogecoin_PIVOT_W 8
#define dogecoin_PIVOT_H 32
extern const metasprite_t* const dogecoin_metasprites[1];

BANKREF_EXTERN(dogecoin)

extern const palette_color_t dogecoin_palettes[4];
extern const uint8_t dogecoin_tiles[64];

#endif
