//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dpadbutton_up_H
#define METASPRITE_dpadbutton_up_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dpadbutton_up_TILE_ORIGIN 194
#define dpadbutton_up_TILE_W 8
#define dpadbutton_up_TILE_H 8
#define dpadbutton_up_WIDTH 16
#define dpadbutton_up_HEIGHT 16
#define dpadbutton_up_TILE_COUNT 4
#define dpadbutton_up_PALETTE_COUNT 1
#define dpadbutton_up_COLORS_PER_PALETTE 4
#define dpadbutton_up_TOTAL_COLORS 4
#define dpadbutton_up_MAP_ATTRIBUTES 0
extern const unsigned char dpadbutton_up_map[4];
#define dpadbutton_up_map_attributes dpadbutton_up_map

BANKREF_EXTERN(dpadbutton_up)

extern const palette_color_t dpadbutton_up_palettes[4];
extern const uint8_t dpadbutton_up_tiles[64];

#endif
