//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dpadbutton_down_H
#define METASPRITE_dpadbutton_down_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dpadbutton_down_TILE_ORIGIN 80
#define dpadbutton_down_TILE_W 8
#define dpadbutton_down_TILE_H 8
#define dpadbutton_down_WIDTH 16
#define dpadbutton_down_HEIGHT 16
#define dpadbutton_down_TILE_COUNT 4
#define dpadbutton_down_PALETTE_COUNT 1
#define dpadbutton_down_COLORS_PER_PALETTE 4
#define dpadbutton_down_TOTAL_COLORS 4
#define dpadbutton_down_MAP_ATTRIBUTES 0
extern const unsigned char dpadbutton_down_map[4];
#define dpadbutton_down_map_attributes dpadbutton_down_map

BANKREF_EXTERN(dpadbutton_down)

extern const palette_color_t dpadbutton_down_palettes[4];
extern const uint8_t dpadbutton_down_tiles[64];

#endif
