//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dpadbutton_right_H
#define METASPRITE_dpadbutton_right_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dpadbutton_right_TILE_ORIGIN 198
#define dpadbutton_right_TILE_W 8
#define dpadbutton_right_TILE_H 8
#define dpadbutton_right_WIDTH 16
#define dpadbutton_right_HEIGHT 16
#define dpadbutton_right_TILE_COUNT 4
#define dpadbutton_right_PALETTE_COUNT 1
#define dpadbutton_right_COLORS_PER_PALETTE 4
#define dpadbutton_right_TOTAL_COLORS 4
#define dpadbutton_right_MAP_ATTRIBUTES 0
extern const unsigned char dpadbutton_right_map[4];
#define dpadbutton_right_map_attributes dpadbutton_right_map

BANKREF_EXTERN(dpadbutton_right)

extern const palette_color_t dpadbutton_right_palettes[4];
extern const uint8_t dpadbutton_right_tiles[64];

#endif
