//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dpadbutton_left_H
#define METASPRITE_dpadbutton_left_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dpadbutton_left_TILE_ORIGIN 85
#define dpadbutton_left_TILE_W 8
#define dpadbutton_left_TILE_H 8
#define dpadbutton_left_WIDTH 16
#define dpadbutton_left_HEIGHT 16
#define dpadbutton_left_TILE_COUNT 4
#define dpadbutton_left_PALETTE_COUNT 1
#define dpadbutton_left_COLORS_PER_PALETTE 4
#define dpadbutton_left_TOTAL_COLORS 4
#define dpadbutton_left_MAP_ATTRIBUTES 0
extern const unsigned char dpadbutton_left_map[4];
#define dpadbutton_left_map_attributes dpadbutton_left_map

BANKREF_EXTERN(dpadbutton_left)

extern const palette_color_t dpadbutton_left_palettes[4];
extern const uint8_t dpadbutton_left_tiles[64];

#endif
