//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_keyboard_lightgrey_H
#define METASPRITE_keyboard_lightgrey_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define keyboard_lightgrey_TILE_ORIGIN 160
#define keyboard_lightgrey_TILE_W 8
#define keyboard_lightgrey_TILE_H 8
#define keyboard_lightgrey_WIDTH 160
#define keyboard_lightgrey_HEIGHT 48
#define keyboard_lightgrey_TILE_COUNT 71
#define keyboard_lightgrey_PALETTE_COUNT 1
#define keyboard_lightgrey_COLORS_PER_PALETTE 4
#define keyboard_lightgrey_TOTAL_COLORS 4
#define keyboard_lightgrey_MAP_ATTRIBUTES keyboard_lightgrey_map_attributes
#define keyboard_lightgrey_MAP_ATTRIBUTES_WIDTH 20
#define keyboard_lightgrey_MAP_ATTRIBUTES_HEIGHT 6
#define keyboard_lightgrey_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define keyboard_lightgrey_MAP_ATTRIBUTES_PACKED_HEIGHT 6
extern const unsigned char keyboard_lightgrey_map[120];
extern const unsigned char keyboard_lightgrey_map_attributes[120];

BANKREF_EXTERN(keyboard_lightgrey)

extern const palette_color_t keyboard_lightgrey_palettes[4];
extern const uint8_t keyboard_lightgrey_tiles[1136];

#endif
