//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_keyboard_H
#define METASPRITE_keyboard_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define keyboard_TILE_ORIGIN 88
#define keyboard_TILE_W 8
#define keyboard_TILE_H 8
#define keyboard_WIDTH 160
#define keyboard_HEIGHT 48
#define keyboard_TILE_COUNT 72
#define keyboard_PALETTE_COUNT 1
#define keyboard_COLORS_PER_PALETTE 4
#define keyboard_TOTAL_COLORS 4
#define keyboard_MAP_ATTRIBUTES keyboard_map_attributes
#define keyboard_MAP_ATTRIBUTES_WIDTH 20
#define keyboard_MAP_ATTRIBUTES_HEIGHT 6
#define keyboard_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define keyboard_MAP_ATTRIBUTES_PACKED_HEIGHT 6
extern const unsigned char keyboard_map[120];
extern const unsigned char keyboard_map_attributes[120];

BANKREF_EXTERN(keyboard)

extern const palette_color_t keyboard_palettes[4];
extern const uint8_t keyboard_tiles[1152];

#endif
