//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_nophotos_H
#define METASPRITE_nophotos_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nophotos_TILE_ORIGIN 150
#define nophotos_TILE_W 8
#define nophotos_TILE_H 8
#define nophotos_WIDTH 112
#define nophotos_HEIGHT 64
#define nophotos_TILE_COUNT 67
#define nophotos_PALETTE_COUNT 1
#define nophotos_COLORS_PER_PALETTE 4
#define nophotos_TOTAL_COLORS 4
#define nophotos_MAP_ATTRIBUTES 0
extern const unsigned char nophotos_map[112];
#define nophotos_map_attributes nophotos_map

BANKREF_EXTERN(nophotos)

extern const palette_color_t nophotos_palettes[4];
extern const uint8_t nophotos_tiles[1072];

#endif
