//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_offlineonly_H
#define METASPRITE_offlineonly_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define offlineonly_TILE_ORIGIN 0
#define offlineonly_TILE_W 8
#define offlineonly_TILE_H 8
#define offlineonly_WIDTH 160
#define offlineonly_HEIGHT 144
#define offlineonly_TILE_COUNT 102
#define offlineonly_PALETTE_COUNT 1
#define offlineonly_COLORS_PER_PALETTE 4
#define offlineonly_TOTAL_COLORS 4
#define offlineonly_MAP_ATTRIBUTES offlineonly_map_attributes
#define offlineonly_MAP_ATTRIBUTES_WIDTH 20
#define offlineonly_MAP_ATTRIBUTES_HEIGHT 18
#define offlineonly_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define offlineonly_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char offlineonly_map[360];
extern const unsigned char offlineonly_map_attributes[360];

BANKREF_EXTERN(offlineonly)

extern const palette_color_t offlineonly_palettes[4];
extern const uint8_t offlineonly_tiles[1632];

#endif
