//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_pepe_idle_H
#define METASPRITE_pepe_idle_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define pepe_idle_TILE_ORIGIN 243
#define pepe_idle_TILE_W 8
#define pepe_idle_TILE_H 8
#define pepe_idle_WIDTH 64
#define pepe_idle_HEIGHT 56
#define pepe_idle_TILE_COUNT 36
#define pepe_idle_PALETTE_COUNT 1
#define pepe_idle_COLORS_PER_PALETTE 4
#define pepe_idle_TOTAL_COLORS 4
#define pepe_idle_MAP_ATTRIBUTES 0
extern const unsigned char pepe_idle_map[56];
#define pepe_idle_map_attributes pepe_idle_map

BANKREF_EXTERN(pepe_idle)

extern const palette_color_t pepe_idle_palettes[4];
extern const uint8_t pepe_idle_tiles[576];

#endif
