//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_pepe_selfbonk_H
#define METASPRITE_pepe_selfbonk_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define pepe_selfbonk_TILE_ORIGIN 202
#define pepe_selfbonk_TILE_W 8
#define pepe_selfbonk_TILE_H 8
#define pepe_selfbonk_WIDTH 72
#define pepe_selfbonk_HEIGHT 56
#define pepe_selfbonk_TILE_COUNT 39
#define pepe_selfbonk_PALETTE_COUNT 1
#define pepe_selfbonk_COLORS_PER_PALETTE 4
#define pepe_selfbonk_TOTAL_COLORS 4
#define pepe_selfbonk_MAP_ATTRIBUTES 0
extern const unsigned char pepe_selfbonk_map[63];
#define pepe_selfbonk_map_attributes pepe_selfbonk_map

BANKREF_EXTERN(pepe_selfbonk)

extern const palette_color_t pepe_selfbonk_palettes[4];
extern const uint8_t pepe_selfbonk_tiles[624];

#endif
