//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_pepelogo_H
#define METASPRITE_pepelogo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define pepelogo_TILE_ORIGIN 0
#define pepelogo_TILE_W 8
#define pepelogo_TILE_H 8
#define pepelogo_WIDTH 160
#define pepelogo_HEIGHT 144
#define pepelogo_TILE_COUNT 98
#define pepelogo_PALETTE_COUNT 1
#define pepelogo_COLORS_PER_PALETTE 4
#define pepelogo_TOTAL_COLORS 4
#define pepelogo_MAP_ATTRIBUTES pepelogo_map_attributes
#define pepelogo_MAP_ATTRIBUTES_WIDTH 20
#define pepelogo_MAP_ATTRIBUTES_HEIGHT 18
#define pepelogo_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define pepelogo_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char pepelogo_map[360];
extern const unsigned char pepelogo_map_attributes[360];

BANKREF_EXTERN(pepelogo)

extern const palette_color_t pepelogo_palettes[4];
extern const uint8_t pepelogo_tiles[1568];

#endif
