//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_pepecoin_H
#define METASPRITE_pepecoin_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define pepecoin_TILE_ORIGIN 202
#define pepecoin_TILE_W 8
#define pepecoin_TILE_H 16
#define pepecoin_WIDTH 8
#define pepecoin_HEIGHT 32
#define pepecoin_TILE_COUNT 4
#define pepecoin_PALETTE_COUNT 1
#define pepecoin_COLORS_PER_PALETTE 4
#define pepecoin_TOTAL_COLORS 4
#define pepecoin_PIVOT_X 4
#define pepecoin_PIVOT_Y 16
#define pepecoin_PIVOT_W 8
#define pepecoin_PIVOT_H 32
extern const metasprite_t* const pepecoin_metasprites[1];

BANKREF_EXTERN(pepecoin)

extern const palette_color_t pepecoin_palettes[4];
extern const uint8_t pepecoin_tiles[64];

#endif
