//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_pepe_bonk_H
#define METASPRITE_pepe_bonk_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define pepe_bonk_TILE_ORIGIN 137
#define pepe_bonk_TILE_W 8
#define pepe_bonk_TILE_H 8
#define pepe_bonk_WIDTH 72
#define pepe_bonk_HEIGHT 56
#define pepe_bonk_TILE_COUNT 40
#define pepe_bonk_PALETTE_COUNT 1
#define pepe_bonk_COLORS_PER_PALETTE 4
#define pepe_bonk_TOTAL_COLORS 4
#define pepe_bonk_MAP_ATTRIBUTES 0
extern const unsigned char pepe_bonk_map[63];
#define pepe_bonk_map_attributes pepe_bonk_map

BANKREF_EXTERN(pepe_bonk)

extern const palette_color_t pepe_bonk_palettes[4];
extern const uint8_t pepe_bonk_tiles[640];

#endif
