//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_progress_bar_H
#define METASPRITE_progress_bar_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>
#pragma bank 10

#define progress_bar_TILE_ORIGIN 0
#define progress_bar_TILE_W 8
#define progress_bar_TILE_H 8
#define progress_bar_WIDTH 184
#define progress_bar_HEIGHT 16
#define progress_bar_TILE_COUNT 46
#define progress_bar_PALETTE_COUNT 1
#define progress_bar_COLORS_PER_PALETTE 4
#define progress_bar_TOTAL_COLORS 4
#define progress_bar_MAP_ATTRIBUTES 0
extern const unsigned char progress_bar_map[46];
#define progress_bar_map_attributes progress_bar_map

BANKREF_EXTERN(progress_bar)

extern const palette_color_t progress_bar_palettes[4];
extern const uint8_t progress_bar_tiles[736];

#endif
